baseURL = 'https://dvliman.github.io'
languageCode = 'en-us'
title = "David Liman"
theme = "hugo-journal"
publishDir = "docs"

[params]
  description = "A product-minded engineer. Clojurian."
  copyright = "Copyright © 2022 David Liman"
  dark = "off"
  highlight = true

[permalinks]
  posts = "/:title/"
