baseURL = 'https://dvliman.github.io/'
languageCode = 'en-us'
title = "David Liman's blog"
theme = "hugo-journal"

[params]
  description = "A product-minded engineer. Clojurian."
  githubUsername = "dvliman"
  twitterUsername = "dvliman"
